-- Eliminar tablas si existen
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BITACORA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ASIGNACION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PRACTICA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USUARIO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 1. Tabla USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    CONTRASENA VARCHAR2(255) NOT NULL,
    ROL VARCHAR2(30) CHECK (ROL IN ('DIRECTOR', 'COORDINADOR', 'ESTUDIANTE', 'TUTOR', 'ASESOR')) NOT NULL
);

-- 2. Tabla PRACTICA
CREATE TABLE PRACTICA (
    ID_PRACTICA NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(150) NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'ABIERTA' CHECK (ESTADO IN ('ABIERTA', 'CERRADA'))
);

-- 3. Tabla ASIGNACION (Gestionar prácticas y grupos)
CREATE TABLE ASIGNACION (
    ID_ASIGNACION NUMBER(10) PRIMARY KEY,
    ID_PRACTICA NUMBER(10) NOT NULL,
    ID_ESTUDIANTE NUMBER(10) NOT NULL,
    ESTADO_APROBACION VARCHAR2(20) DEFAULT 'PENDIENTE' CHECK (ESTADO_APROBACION IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')),
    FOREIGN KEY (ID_PRACTICA) REFERENCES PRACTICA(ID_PRACTICA),
    FOREIGN KEY (ID_ESTUDIANTE) REFERENCES USUARIO(ID_USUARIO)
);

-- 4. Tabla BITACORA (Actividades y evidencias, consultar horas)
CREATE TABLE BITACORA (
    ID_BITACORA NUMBER(10) PRIMARY KEY,
    ID_ASIGNACION NUMBER(10) NOT NULL,
    FECHA DATE NOT NULL,
    HORAS NUMBER(4) NOT NULL,
    DESCRIPCION VARCHAR2(500) NOT NULL,
    URL_EVIDENCIA VARCHAR2(200),
    FOREIGN KEY (ID_ASIGNACION) REFERENCES ASIGNACION(ID_ASIGNACION)
);

-- Insertar Datos de Prueba (Contraseñas cifradas con bcrypt para '1234')
INSERT INTO USUARIO (ID_USUARIO, NOMBRE, EMAIL, CONTRASENA, ROL) VALUES (1, 'Ana Director', 'director@sigpa.edu', '$2b$10$bOrLbbmzQrt3RU7SV/zUceAVhV3vgdkMjAv9qGV8SFJDqkbmJDf7.', 'DIRECTOR');
INSERT INTO USUARIO (ID_USUARIO, NOMBRE, EMAIL, CONTRASENA, ROL) VALUES (2, 'Carlos Coordinador', 'coord@sigpa.edu', '$2b$10$bOrLbbmzQrt3RU7SV/zUceAVhV3vgdkMjAv9qGV8SFJDqkbmJDf7.', 'COORDINADOR');
INSERT INTO USUARIO (ID_USUARIO, NOMBRE, EMAIL, CONTRASENA, ROL) VALUES (3, 'Laura Estudiante', 'estudiante@sigpa.edu', '$2b$10$bOrLbbmzQrt3RU7SV/zUceAVhV3vgdkMjAv9qGV8SFJDqkbmJDf7.', 'ESTUDIANTE');

INSERT INTO PRACTICA (ID_PRACTICA, NOMBRE, ESTADO) VALUES (1, 'Práctica Observación Nivel 1', 'ABIERTA');
INSERT INTO PRACTICA (ID_PRACTICA, NOMBRE, ESTADO) VALUES (2, 'Práctica Intervención Nivel 2', 'ABIERTA');

INSERT INTO ASIGNACION (ID_ASIGNACION, ID_PRACTICA, ID_ESTUDIANTE, ESTADO_APROBACION) VALUES (1, 1, 3, 'APROBADA');

INSERT INTO BITACORA (ID_BITACORA, ID_ASIGNACION, FECHA, HORAS, DESCRIPCION, URL_EVIDENCIA) VALUES (1, 1, SYSDATE - 5, 4, 'Observación en aula de clase', 'http://drive.link/foto1');

COMMIT;
